from fastapi import APIRouter
from fastapi.responses import FileResponse
from sqlalchemy import text
from database.db import engine

from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    HRFlowable
)

from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)

from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors

router = APIRouter()


@router.get("/download-summary/{id}")
def download_summary(id: int):

    with engine.connect() as conn:

        result = conn.execute(
            text("""
                SELECT
                    file_name,
                    summary
                FROM document_summaries
                WHERE id = :id
            """),
            {"id": id}
        )

        row = result.fetchone()

    if not row:
        return {"message": "Summary not found"}

    pdf_file = f"summary_{id}.pdf"

    doc = SimpleDocTemplate(
        pdf_file,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        alignment=TA_CENTER,
        textColor=colors.darkblue,
        fontSize=24,
        spaceAfter=5
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Heading2"],
        alignment=TA_CENTER,
        textColor=colors.grey,
        fontSize=12,
        spaceAfter=20
    )

    heading_style = ParagraphStyle(
        "HeadingStyle",
        parent=styles["Heading2"],
        textColor=colors.darkblue,
        fontSize=15,
        spaceBefore=12,
        spaceAfter=8
    )

    body_style = ParagraphStyle(
        "BodyStyle",
        parent=styles["BodyText"],
        fontSize=11,
        leading=18,
        spaceAfter=8
    )

    bullet_style = ParagraphStyle(
        "BulletStyle",
        parent=body_style,
        leftIndent=20,
        bulletIndent=10
    )

    footer_style = ParagraphStyle(
        "FooterStyle",
        parent=styles["BodyText"],
        alignment=TA_CENTER,
        textColor=colors.grey,
        fontSize=9
    )

    content = []

    # ==========================
    # HEADER
    # ==========================

    content.append(
        Paragraph(
            " AccredAI",
            title_style
        )
    )

    content.append(
        Paragraph(
            "Hospital Accreditation AI Platform",
            subtitle_style
        )
    )

    content.append(
        HRFlowable(
            width="100%",
            thickness=1,
            color=colors.darkblue
        )
    )

    content.append(Spacer(1, 15))

    # ==========================
    # DOCUMENT INFORMATION
    # ==========================

    content.append(
        Paragraph(
            "DOCUMENT INFORMATION",
            heading_style
        )
    )

    content.append(
        Paragraph(
            f"<b>File Name:</b> {row.file_name}",
            body_style
        )
    )

    content.append(
        Paragraph(
            "<b>Generated By:</b> AccredAI Platform",
            body_style
        )
    )

    content.append(
        Paragraph(
            f"<b>Generated On:</b> {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            body_style
        )
    )

    content.append(Spacer(1, 10))

    content.append(
        HRFlowable(
            width="100%",
            thickness=0.7,
            color=colors.lightgrey
        )
    )

    content.append(Spacer(1, 15))

    # ==========================
    # SUMMARY
    # ==========================

    summary = row.summary.replace("**", "")
    summary = summary.replace("* ", "- ")

    lines = summary.split("\n")

    headings = [
        "Policy Name",
        "Purpose",
        "Key Areas Covered",
        "Compliance Highlights",
        "Overall Assessment"
    ]

    for line in lines:

        line = line.strip()

        if not line:
            continue

        if any(h in line for h in headings):

            content.append(
                Paragraph(
                    line.upper(),
                    heading_style
                )
            )

        elif line.startswith("-"):

            line = line.replace("-", "•", 1)

            content.append(
                Paragraph(
                    line,
                    bullet_style
                )
            )

        else:

            content.append(
                Paragraph(
                    line,
                    body_style
                )
            )

    # ==========================
    # FOOTER
    # ==========================

    content.append(Spacer(1, 25))

    content.append(
        HRFlowable(
            width="100%",
            thickness=0.7,
            color=colors.lightgrey
        )
    )


    doc.build(content)

    return FileResponse(
        pdf_file,
        media_type="application/pdf",
        filename=f"Document_Summary_{id}.pdf"
    )